name: Build API

on:
  push:
    branches: [main, develop]
    paths:
      - 'apps/api/**'
      - 'package.json'
      - 'package-lock.json'
      - 'nx.json'
      - 'tsconfig.base.json'
  pull_request:
    branches: [main, develop]
    paths:
      - 'apps/api/**'
      - 'package.json'
      - 'package-lock.json'
      - 'nx.json'
      - 'tsconfig.base.json'

permissions:
  contents: read

jobs:
  build-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Lint API
        run: npx nx lint api

      - name: Build API
        run: npx nx build api

      - name: Upload API build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: api-build-${{ github.sha }}
          path: apps/api/dist/
          retention-days: 7

      - name: Check build output
        run: |
          echo "API build completed successfully!"
          ls -la apps/api/dist/
          echo "Build size:"
          du -sh apps/api/dist/
